update FIX workshop
coinbase-samples/prime-scripts-py pull request #12
Opened 2023-02-23 13:38 UTC by jc-cb

see slack for change log

2023-02-23 15:30 UTC, nmorgancb commented on FIX/app/configuration.py
> +# Copyright 2023 Coinbase Global, Inc.
2023-present

2023-02-27 16:43 UTC, rcbgr requested changes

2023-02-27 16:43 UTC, rcbgr commented on FIX/app/fix_session.py
> +        #logfix.info('Session (%s) logout!' % sessionID.toString())
Remove this commented out string?

2023-02-27 16:43 UTC, rcbgr commented on FIX/app/fix_session.py
> +
Remove extra line

2023-02-27 16:43 UTC, rcbgr commented on LICENSE
> +   Copyright 2023 Coinbase Global, Inc.
2023-present

2023-03-01 17:44 UTC, jprix approved these changes

2023-03-01 18:16 UTC, rcbgr approved these changes

2023-03-01 18:16 UTC, merged

2024-07-21 12:02 UTC, KMORGAN008 approved these changes

2024-07-21 12:03 UTC, KMORGAN008 commented
e8f76d65c46b580e52f5bbea5f5a31781fd8b1a0